version: '3.8'

services:
  wechat-api:
    build:
      context: .
      dockerfile: Dockerfile.net8
    image: 43.138.35.183/wechat-api:net8-latest
    container_name: wechat-api-net8
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./certificates:/app/certificates:ro
      - ./uploadall:/app/wwwroot/uploadall
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - wechat-network

networks:
  wechat-network:
    driver: bridge